{
  "openapi": "3.0.0",
  "info":
    {
      "title": "FastAPI Service",
      "version": "1.0.0",
      "description": "This is an API service for managing RSS feeds and entries.",
    },
  "paths":
    {
      "/health":
        {
          "get":
            {
              "summary": "Health Check",
              "description": "Check the health of all services.",
              "responses":
                {
                  "200":
                    {
                      "description": "Health check successful",
                      "content":
                        {
                          "application/json":
                            {
                              "schema":
                                {
                                  "type": "object",
                                  "example": { "status": "healthy" },
                                },
                            },
                        },
                    },
                  "500": { "description": "Health check failed" },
                },
            },
        },
      "/feeds/":
        {
          "post":
            {
              "summary": "Create Feed",
              "description": "Create a new feed and fetch its entries in the background.",
              "requestBody":
                {
                  "required": true,
                  "content":
                    {
                      "application/json":
                        {
                          "schema":
                            { "$ref": "#/components/schemas/FeedCreate" },
                        },
                    },
                },
              "responses":
                {
                  "200":
                    {
                      "description": "Feed created successfully",
                      "content":
                        {
                          "application/json":
                            {
                              "schema": { "$ref": "#/components/schemas/Feed" },
                            },
                        },
                    },
                  "400": { "description": "Invalid RSS feed URL" },
                  "500": { "description": "Internal server error" },
                },
            },
          "get":
            {
              "summary": "Get Feeds",
              "description": "Retrieve all feeds.",
              "responses":
                {
                  "200":
                    {
                      "description": "Feeds retrieved successfully",
                      "content":
                        {
                          "application/json":
                            {
                              "schema":
                                {
                                  "type": "array",
                                  "items":
                                    { "$ref": "#/components/schemas/Feed" },
                                },
                            },
                        },
                    },
                  "500": { "description": "Internal server error" },
                },
            },
        },
      "/feeds/{feed_id}":
        {
          "get":
            {
              "summary": "Get Feed",
              "description": "Retrieve a specific feed by ID.",
              "parameters":
                [
                  {
                    "name": "feed_id",
                    "in": "path",
                    "required": true,
                    "schema": { "type": "string" },
                  },
                ],
              "responses":
                {
                  "200":
                    {
                      "description": "Feed retrieved successfully",
                      "content":
                        {
                          "application/json":
                            {
                              "schema": { "$ref": "#/components/schemas/Feed" },
                            },
                        },
                    },
                  "404": { "description": "Feed not found" },
                  "500": { "description": "Internal server error" },
                },
            },
          "put":
            {
              "summary": "Update Feed",
              "description": "Update a feed's information.",
              "parameters":
                [
                  {
                    "name": "feed_id",
                    "in": "path",
                    "required": true,
                    "schema": { "type": "string" },
                  },
                ],
              "requestBody":
                {
                  "required": true,
                  "content":
                    {
                      "application/json":
                        {
                          "schema":
                            { "$ref": "#/components/schemas/FeedUpdate" },
                        },
                    },
                },
              "responses":
                {
                  "200":
                    {
                      "description": "Feed updated successfully",
                      "content":
                        {
                          "application/json":
                            {
                              "schema": { "$ref": "#/components/schemas/Feed" },
                            },
                        },
                    },
                  "404": { "description": "Feed not found" },
                  "500": { "description": "Internal server error" },
                },
            },
          "delete":
            {
              "summary": "Delete Feed",
              "description": "Delete a feed and its associated entries.",
              "parameters":
                [
                  {
                    "name": "feed_id",
                    "in": "path",
                    "required": true,
                    "schema": { "type": "string" },
                  },
                ],
              "responses":
                {
                  "200":
                    {
                      "description": "Feed deleted successfully",
                      "content":
                        {
                          "application/json":
                            {
                              "schema":
                                {
                                  "type": "object",
                                  "example":
                                    {
                                      "status": "success",
                                      "message": "Feed deleted",
                                      "deleted": true,
                                    },
                                },
                            },
                        },
                    },
                  "404": { "description": "Feed not found" },
                  "500": { "description": "Internal server error" },
                },
            },
        },
      "/entries/":
        {
          "get":
            {
              "summary": "Get Entries",
              "description": "Retrieve entries with optional keyword filtering.",
              "parameters":
                [
                  {
                    "name": "limit",
                    "in": "query",
                    "schema": { "type": "integer", "default": 10 },
                  },
                  {
                    "name": "skip",
                    "in": "query",
                    "schema": { "type": "integer", "default": 0 },
                  },
                  {
                    "name": "keywords",
                    "in": "query",
                    "schema":
                      { "type": "array", "items": { "type": "string" } },
                  },
                ],
              "responses":
                {
                  "200":
                    {
                      "description": "Entries retrieved successfully",
                      "content":
                        {
                          "application/json":
                            {
                              "schema":
                                {
                                  "$ref": "#/components/schemas/PaginatedEntriesResponse",
                                },
                            },
                        },
                    },
                  "500": { "description": "Internal server error" },
                },
            },
        },
    },
  "components":
    {
      "schemas":
        {
          "Feed":
            {
              "type": "object",
              "properties":
                {
                  "id": { "type": "string" },
                  "url": { "type": "string" },
                  "created_at": { "type": "string", "format": "date-time" },
                  "updated_at": { "type": "string", "format": "date-time" },
                },
            },
          "FeedCreate":
            {
              "type": "object",
              "properties": { "url": { "type": "string" } },
              "required": ["url"],
            },
          "FeedUpdate":
            { "type": "object", "properties": { "url": { "type": "string" } } },
          "Entry":
            {
              "type": "object",
              "properties":
                {
                  "id": { "type": "string" },
                  "title": { "type": "string" },
                  "link": { "type": "string" },
                  "published_at": { "type": "string", "format": "date-time" },
                },
            },
          "PaginatedEntriesResponse":
            {
              "type": "object",
              "properties":
                {
                  "entries":
                    {
                      "type": "array",
                      "items": { "$ref": "#/components/schemas/Entry" },
                    },
                  "total_count": { "type": "integer" },
                },
            },
        },
    },
}
